### ISSUE TITLE
Update language repo names

### ISSUE THREAD

**Issue by aspina7** [appliedepi/epiRhandbook_eng#10]
Nice to have but: 
in the process of reducing the repo size (#6) we could also consider standardising the repo language name extensions to either be [3-letter ISO codes](https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes) or [country domains](https://en.wikipedia.org/wiki/Country_code_top-level_domain#Lists)

**Comment by jarvisc1** [comment]
Close old issues.
