### ISSUE TITLE
No tag on Reports with Markdown , GGplot tips and GGplot basics pages

### ISSUE THREAD

**Issue by aminatand** [appliedepi/epiRhandbook_eng#100]
Please add {#rmakdown} , {#ggplot_basics}, {#ggplot_tips} as tags after the titles for these pages

**Comment by jcfernandezm** [comment]
I do agree with that point. I think it will simplify translations. And, probably an approximate approach with sub-chapters tag (those with ##). When link from one chapter to a specific section of another chapter  doesn't goes. In my case, as we (spanish translation) started with a word document the problem can be minor, but if you translate over the code .....
