### ISSUE TITLE
Bad link in chapter 42

### ISSUE THREAD

**Issue by jcfernandezm** [appliedepi/epiRhandbook_eng#101]
The link in "Section attributes" 
     * See complete size documentation at the [flexdashboard website](https://rmarkdown.rstudio.com/flexdashboard/using.html#sizing)  
does not works
the correct address is 
https://pkgs.rstudio.com/flexdashboard/articles/using.html#sizing

**Comment by jcfernandezm** [comment]
And later there are a similar error,
Below we give a very simple example using the same "outbreak_dashboard.Rmd" as above. Extensive documentation on integrating Shiny into **flexdashboard** is available online [here](https://rmarkdown.rstudio.com/flexdashboard/shiny.html).  

The correct is https://pkgs.rstudio.com/flexdashboard/articles/shiny.html

**Comment by jcfernandezm** [comment]
And two more (sorry)
Into the Resources section, the corrects links are 
https://pkgs.rstudio.com/flexdashboard/articles/using.html
https://pkgs.rstudio.com/flexdashboard/articles/examples.html

**Comment by arranhamlet** [comment]
Thank you for flagging this, it has now been updated
