### ISSUE TITLE
migrating to a github organisation

### ISSUE THREAD

**Issue by aspina7** [appliedepi/epiRhandbook_eng#11]
hey neale - just realised it might be useful to migrate this to a github organisation rather than having it as a standalone repo. 
Think it makes it easier to manage and can have multiple repos within it etc. 
maybe not necessary though

**Comment by nsbatra** [comment]
Thanks for pointing out this option.  It looks like organizations really helps when working across multiple repositories. What other repos are you thinking of?

**Comment by aspina7** [comment]
Don't know what other repos might be necessary (?). Really just thought
might be easier for managing admin rights ,... Might be same same tho
