### ISSUE TITLE
No direct link to download the relationships_clean.rds dataset in chapter 25 "Contact tracing"

### ISSUE THREAD

**Issue by mcewenkhundi** [appliedepi/epiRhandbook_eng#110]
Dear Authors,

Chapter 25 has 4 sample data sets. Three have direct download links except one, the relationships_clean dataset. It is also not possible to download it using get_data() function. I had to directly get it from the linked source page https://github.com/WorldHealthOrganization/godata/blob/master/analytics/r-reporting/data/relationships_clean.rds

Again thank you for all the hard work. 

<img width="505" alt="Capture" src="https://user-images.githubusercontent.com/40823168/172847534-1a90d5af-c5ee-4fab-9d62-e65107e6a72e.PNG">

**Comment by arranhamlet** [comment]
Thank you for flagging this, it has now been updated
