### ISSUE TITLE
Sugestion: mention base R pipe

### ISSUE THREAD

**Issue by cievsdf** [appliedepi/epiRhandbook_eng#112]
Just a suggestion, to mention the existence of a of pipe ( |> ), in Base R https://www.infoworld.com/article/3621369/use-the-new-r-pipe-built-into-r-41.html

**Comment by aratikrish** [comment]
Note that the 2nd edition of R4DS recommends the base pipe (https://r4ds.hadley.nz/data-transform#sec-the-pipe). It might make sense to switch all code to the base pipe with mention of the older magrittr pipe and where the key differences lie (base pipe only works with pipe friendly functions where the first argument is the value passed in through the pipe and base pipe requires parenthesis at the end of the function even if there are no arguments other than the value being passed (which is good coding style anyway)

**Comment by arranhamlet** [comment]
The new version will be updated with these changes, thank you both for highlighting this.
