### ISSUE TITLE
Feedback: Survival Analysis

### ISSUE THREAD

**Issue by dmolling** [appliedepi/epiRhandbook_eng#114]
Overall, this page looks great! I'll make some specific pull requests for smaller issues, but here are some general thoughts I have:

**Overview**

- I'd prefer to have less emphasis on describing events as the "failure". That's a pretty specific term, and I've more commonly seen just "event" or "time-to-event" used rather than failure and failure time, ect. 
- When describing right censoring, we could add something like "which occurs when we are missing information for a subject _after_ a certain point in time"

**Data management and transformation**

- I'd like to add a section here where we talk about dates in more detail, and give a brief overview of using the lubridate package for working with dates. I'll add a draft for that. 
- While it is good practice to check results of code, I think we can exclude some of these checks from the chapter to stay more focused. Maybe just keep the block where you show the head of the dataset, but drop some of the other tables. 

**Basics of survival analysis**

- I think it would be good to add a little more detail about what a survival function is and what survival probability means before going into the section on building a surv object. I'll add a draft for that. 

**Plotting Kaplan-Meir curves**

I like how you describe KM curves here. Even though you talk about the survminer package stuff later I think it would be nice to introduce it here as an alternative to using base R to plot survival curves. 

**Other comments**

- I think we should add a section on time-dependent covariates. I can work on that. 
- I also think a  section on competing risks would be good to have. I can also work on that. 

Again, good stuff!

**Comment by nsbatra** [comment]
Thanks for your comments Daniel! Tagging @aminatand  so she gets notified of this and you two can coordinate.

**Comment by dmolling** [comment]
Ah, I forgot to tag Aminata! Thank you.

**Comment by aminatand** [comment]
Hey Daniel, Thanks for the detailed comments. I do also agree to add the part on competing risks. I will wait for you inputs before applying the final corrections!

**Comment by nsbatra** [comment]
Hi both,
I've merged Daniel's new section, so Aminata please make your
corrections/edits when you are able to. This page is looking very nice!
Thanks again,
Neale
