### ISSUE TITLE
Fix broken link for Isaac Florence in README page

### ISSUE THREAD

**Issue by shahronak47** [appliedepi/epiRhandbook_eng#116]
The hyperlink for Isaac Florence in README redirects to https://github.com/appliedepi/epiRhandbook_eng/blob/master/www.Twitter.com/isaacatflorence which is an invalid URL. Maybe you meant https://twitter.com/isaacatflorence

**Comment by arranhamlet** [comment]
Thank you, we have updated the twitter links in the upcoming version.
