### ISSUE TITLE
Feedback: Pivoting data

### ISSUE THREAD

**Issue by nsbatra** [appliedepi/epiRhandbook_eng#119]
Lead author is @jpolonsky

**Comment by nsbatra** [comment]
@jpolonsky 
Here is some feedback from a reviewer at Epicentre (via Google form review). Do you have time to address and incorporate?

**Suggestions for the organization of this page**
I am not fully convinced about the order/structure, but it may be partially cultural, specific/example-to-general vs. general-to-specific/example). How I would see it:

Introductory paragraph (as is).

Section : Tidy data (whatever else you choose to reorder, this way of thinking about data deserves a real introductory paragraph at the begining of a chapter, with it's own title, not a quick mention lost in the middle of the rest.

Section : long vs wide dataframes. With the same screenshot that is used later but without the arrows. Plus a couple of sentences to expain : 
- why it is called that way
- advantages of both (a lot of analyses will call for "longer" format, plotting as well, while presenting the tables and entering data may be easier in a somewhat "larger" format).
- it is not white and grey but depends on use (the reason the functions are called piwot_widER and pivot_largER).
Basically, most of these information is scattered in different sections in the page, and I would find it extremely frustrating to prepare a dataset when I do not even know what we are going to discuss.

Section : Preparation
And the other sections in the same order as now. 


**Suggestions for technical content of this page**
If you want this book to be a reference without the internet, then I strongly suggest that you go over the more complexes cases for pivots (multiple pivoting, splitting columns by name...). Because columns that mix two different variables occur regularly in epi data (my favourite example of the moment is the WHO Covid aggregated data template, where columns mix age groups, sex, and type of obs (death/cases)

There is a trouble I encountered recently doing a pivot longer then wider, the pivot_wider created nested columns because the rest of the columns were not making unique reccord. Knowing the tidyverse, I was able to quickly understand the warning, but my collegue who is new to this set of packages had no idea what list-columns/nested columns were and was quite confused. Mayby it would be good to mention that if there are multiples lines for one "record" R will store all the raws into a list within a column, and make a link to an introduction to list columns without going into details about what they are?

**Suggestions for technical content of this page**
If you want this book to be a reference without the internet, then I strongly suggest that you go over the more complexes cases for pivots (multiple pivoting, splitting columns by name...). Because columns that mix two different variables occur regularly in epi data (my favourite example of the moment is the WHO Covid aggregated data template, where columns mix age groups, sex, and type of obs (death/cases)

There is a trouble I encountered recently doing a pivot longer then wider, the pivot_wider created nested columns because the rest of the columns were not making unique reccord. Knowing the tidyverse, I was able to quickly understand the warning, but my collegue who is new to this set of packages had no idea what list-columns/nested columns were and was quite confused. Mayby it would be good to mention that if there are multiples lines for one "record" R will store all the raws into a list within a column, and make a link to an introduction to list columns without going into details about what they are?

**What else do you want to tell us?**
There is one ressource I LOVE and I strongly suggest you reference it. It is my go-to site when I want to do more complex things than single variable pivoting : https://speakerdeck.com/yutannihilation/a-graphical-introduction-to-tidyrs-pivot-star?slide=5

**Comment by daniellybx** [comment]
Hi,

11.3 Long-to-wide
In section 11.3 Long-to-wide we could indicate the reshape and reshape2 packages, using the "reshape" and "melt" functions.
In this excerpt, it's also important to note that some functions work better with a certain data.frame configuration. For example, some graphics in ggplot work best when we have data in long format. While the layout of tables to be exported may be better in "wide" format.

**Comment by jpolonsky** [comment]
Thanks for the comments @daniellybx. My understanding is that {reshape2} has been retired in favour of {tidyr}, so I'm hesitant to introduce new users to that 📦. `melt()` and `cast()` have been replaced by `pivot_longer()` and `pivot_wider()`, respectively. 

Thanks for the comment about data formats in {ggplot2} - it's a good point and should be emphasised 👍

**Comment by jpolonsky** [comment]
@nsbatra Thanks for posting that comment and the link to that resource. I have gone through it in detail and find some of it very useful and important. Therefore I will include the pivoting multiple columns at once material, but I think the splitting columns by name is a general task that is not specific to pivoting, and should be covered elsewhere using the `separate()` function, rather than an argument from within the `pivot_*()` family. There are one or two other things in there that I think are too complex for the usual needs of the end user and inclusion would risk over-complicating things...

**Comment by nsbatra** [comment]
Thanks for looking through that link Jonny, and I'm glad you found some of
it useful. That sounds like a good plan to move forward with select
additions.
Please keep me up-to-date on developments - I am just trying to keep tabs
on many pieces as we wrap this up!
