### ISSUE TITLE
Feedback: Epidemic models

### ISSUE THREAD

**Issue by nsbatra** [appliedepi/epiRhandbook_eng#120]
Lead author is @finlaycampbell

**Comment by JWr1gh7** [comment]
Hey Finlay!

Got no comments on the code itself, but a few small suggestions.

24.3/EpiNow2 - in section about get_pairwise from epicontacts – add link to section where you mention that further info can be found in the Transmission chains chapter 

24.3/Running EpiNow2 – final bullet point before the code section “We pass additional options to the stan argument to specify how how long ...“ remove second “how” 

24.3/EpiEstim - “We will create an incidence object. The page on Epidemic curves for more examples with the incidence2 package.” -- add “**See** the page on Epidemic curves …" 

24.3/EpiEstim/Using serial interval estimates from the data – as above, add link to Transmission chains chapter when mentioned 

24.3/EpiEstim/Specifying estimation time windows -- These default options will provide a weekly sliding estimate and might **act as** a warning that you are estimating Rt too early 

24.3/EpiEstim/Analysing outputs -- The main outputs can be access**ed** via $R 

24.4/EpiNow2 -- see the EpiNow2 section under the “Estimating Rt” **heading** 

24.4/EpiNow2/projections -- Here we will cover how to use serial interval estimates from the literature and how to use our own estimates **from** the linelist. 

24.4/EpiNow2/Using serial interval estimates from the literature - Here **is** a quick check to make sure the serial interval looks correct. 

24.4/EpiNow2/Using serial interval estimates from the data – again, add link to Transmission chains chapter 

Great work!

**Comment by nsbatra** [comment]
James, thanks for taking the time to review the page, and for these comments! 
@finlaycampbell don't worry about these typos & links etc - I'll take care of them. I know you're busy.
