### ISSUE TITLE
Bad link in chap 16, Resources section

### ISSUE THREAD

**Issue by jcfernandezm** [appliedepi/epiRhandbook_eng#120]
At the resources section:
[purrr tips and tricks](https://www.hvitfeldt.me/blog/purrr-tips-and-tricks/)

This link call an extrange page for diamonds, gold, etc

I think, the correct one is
[purrr tips and tricks](https://www.emilhvitfeldt.com/post/2018-01-08-purrr-tips-and-tricks/)

**Comment by nsbatra** [comment]
Gracias. This has been fixed in the English version code and will be corrected when it is next rendered.
