### ISSUE TITLE
Minor typos in "9 Working with dates"

### ISSUE THREAD

**Issue by jaehyoungtlee** [appliedepi/epiRhandbook_eng#122]
- 9.3 Convert to date - base R: strptime abbreviation list %w = Weekday number (0-6, Sunday is 0) should be a new line
- 9.4 Excel dates: missing `"` at the end of `as.numeric(as.Date("1970-01-01))`

**Comment by arranhamlet** [comment]
Thank you for flagging this, it has now been updated
