### ISSUE TITLE
Consider Github Large File Storage (LFS)

### ISSUE THREAD

**Issue by aspina7** [appliedepi/epiRhandbook_eng#13]
As suggested by Bassem we might want to look at the pricing plans for [github large file storage](https://docs.github.com/en/github/managing-large-files/versioning-large-files/about-storage-and-bandwidth-usage) if our clean up in (#6) still leaves us with a heavy load.

**Comment by aspina7** [comment]
also consider other options (listed in the {pins} link) such as using [nextcloud ](https://nextcloud.com/) together with the {[pins](https://pins.rstudio.com/articles/boards-understanding.html)} package

**Comment by jarvisc1** [comment]
Possibly want to look at this one?

**Comment by aspina7** [comment]
nah dont think we will need - with reorg it will all be small enough, even the data repos should be negligible. Can circle back in the future if we think it could be useful for projects, but I doubt it because data security. Will close now, but feel free to re-open if disagree.
