### ISSUE TITLE
Check for Outdated Links

### ISSUE THREAD

**Issue by Luccan97** [appliedepi/epiRhandbook_eng#132]
It looks like some links along the book changed. I will list some that I identified, it is possible that other links are also broken because after the Posit rebrand there were some changes to the website.

1) [RStudio user interface cheatsheet](https://epirhandbook.com/en/r-basics.html#keyboard-shortcuts) 
* [Broken link](https://www.rstudio.com/wp-content/uploads/2016/01/rstudio-IDE-cheatsheet.pdf)
* [Correct link](https://posit.co/wp-content/uploads/2022/10/rstudio-ide-1.pdf)

2) [The tidyverse page on joins on 14.5 Resources](https://epirhandbook.com/en/joining-data.html#resources-7)
* [Broken link](https://dplyr.tidyverse.org/reference/join.html)
* Correct link not found

**Comment by beansrowning** [comment]
> 3\. [The tidyverse page on joins on 14.5 Resources](https://epirhandbook.com/en/joining-data.html#resources-7)
> 
> * [Broken link](https://dplyr.tidyverse.org/reference/join.html)
> * Correct link not found

I think this is now called "two-table verbs": https://dplyr.tidyverse.org/articles/two-table.html
