### ISSUE TITLE
Typo in section 27.3 Basics of survival analysis

### ISSUE THREAD

**Issue by clayford** [appliedepi/epiRhandbook_eng#139]
Second paragraph.

"This object will ultimately be used in the right-hand side of subsequent model formulae" should be " This object will ultimately be used in the **left**-hand side of subsequent model formulae"

Also, in the following code chunk, "Suv()" should be "Surv()" in the comment.

**Comment by arranhamlet** [comment]
Thank you for flagging this, it has now been updated
