### ISSUE TITLE
Missing data imputation - final touch-ups

### ISSUE THREAD

**Issue by nsbatra** [appliedepi/epiRhandbook_eng#161]
Hey @dmolling! 

I was reviewing the missing data page and noticed two notes from you to yourself in the imputation section. Are these things I can ignore/erase? Are you able to finish them up? screenshots below:  
Thanks!

https://epirhandbook.com/missing-data.html#imputation

![image](https://user-images.githubusercontent.com/52152191/117239378-a8c86000-adfc-11eb-9f63-d1d8e06d42a8.png)

![image](https://user-images.githubusercontent.com/52152191/117239463-cc8ba600-adfc-11eb-9a37-761dba04ade5.png)

**Comment by dmolling** [comment]
Ahh, I forgot about that. I really should fill out the LOCF and BOCF
sections. Yes, I'll add code for that.I think that other model is actually
fine though--I might just add a little caveat that it's an overly simple
model. I'll clean that up tomorrow afternoon.

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
