### ISSUE TITLE
time series errors

### ISSUE THREAD

**Issue by nsbatra** [appliedepi/epiRhandbook_eng#174]
@aspina7  if you have some time I need help troubleshooting the time series page.

I've been updating the book to R 4.1 and encountered errors in the time series page (branch is "30May_minorupdates"). Can you see if they occur for you? See below how I fixed some of them and please tell me if this is a problem (e.g. methodologically). Also at the end I could not resolve one issue.

Feel free to edit directly into this branch ("30May_minorupdates")

I would get error like this when the `predict()` function was applied (e.g. around line 747 after introduction of the lagged variable). This happened in two places:
![image](https://user-images.githubusercontent.com/52152191/120248300-8f240800-c244-11eb-9a7d-9791d7f16a3e.png)

I solved them by dropping rows with missing values (`drop_na()`) prior to the predict function, such as just after the lagged column is created. 

![image](https://user-images.githubusercontent.com/52152191/120248269-79aede00-c244-11eb-96a0-aa60bd1096d8.png)

and here:

![image](https://user-images.githubusercontent.com/52152191/120248527-93045a00-c245-11eb-9040-f804f1f2b9b6.png)

Then, at row 1249 (within the purrr function) I was getting this error:

![image](https://user-images.githubusercontent.com/52152191/120249367-a533c780-c248-11eb-8311-f74d2d4db364.png)

So I removed the `case_int` column, which was full of NA's when I tested the function using i = 53. Then the purrr function worked. 

![image](https://user-images.githubusercontent.com/52152191/120249406-cb596780-c248-11eb-94c4-1cab6fcfd904.png)

Then in section with farringtonFlexible (around line 1345) I encountered this error I could not resolve. I wonder if it is because I've shortened the `counts` object trying to resolve the earlier issues, and now it doesn't align with the start and cutoff dates:
`farringtonmethod <- farringtonFlexible(counts_sts, ctrl)`

![image](https://user-images.githubusercontent.com/52152191/120249731-d06ae680-c249-11eb-8f14-5a7d7e274adf.png)

**Comment by nsbatra** [comment]
P.S. You'll notice a bunch of edits to the epicurves page in this branch. That was the original reason for the update. Incidence2 has been updated.

**Comment by aspina7** [comment]
not sure whats going on tbh - potentially changes to {trending}. Will update to 4.1 this afternoon and then take a look at trending and get to the bottom of it!

**Comment by nsbatra** [comment]
Thanks for taking a look, Alex

**Comment by aspina7** [comment]
@tjtnew hey tim - running in to an error with the timeseries page here and it seems there might have been some breaking changes in the new version of {trending}? 
If look at Neale's comments above - the second bit from "and here:" onwards - (have tagged you in the code separately). 
Basically the scenario is: we are pretending to be currently in the middle of 2011, and so there is no counts data from kind of mid july till the end of the year. We fit the regression to the baseline time period and then use that to predict for the whole of 2011 (also for weeks where there is no counts data available). 
In the previous package version this worked a treat - but now only does for the weeks with counts available.

**Comment by tjtnew** [comment]
Hi @aspina7. So on the April 19th release we changed the default for `predict` to be simulate/bootstrapped predictions intervals using the `ciTools` package. My guess is you are running in to an issue there.  Could you try with the `simulate_pi = FALSE` as an argument to `predict` and see if that gets you back to the old behaviour.

@nsbatra I'm a bit pressed now and about to take a few weeks break but when I'm back shall we discuss replicating some of the Handbook examples as snapshot tests in the relevant RECON packages? That whey I can see if I cause any breakages when I'm developing things and either fix them then or give you early warning.

**Comment by nsbatra** [comment]
@tjtnew thank you so much for the quick response and @aspina7 for the turnaround on the time series page. The handbook has just been updated to R4.1 and incidence2 v1.1. The new capabilities look great and will be much appreciated by the readers.

Tim - do have a relaxing, well-deserved break. Yes, let's brainstorm when you get back about stability and versioning.
