### ISSUE TITLE
Error (?) in epidemic curves (32.3)

### ISSUE THREAD

**Issue by PBBlomquist** [appliedepi/epiRhandbook_eng#180]
Received email whether weekly_breaks_central should be used instead of weekly_breaks_all?

Email:

Who do I let know if there are errors in the code or if things don’t work eg Epidemic curves section – 32.3 – section on group/color by value– code highlighted below should be weekly¬_breaks_central I think (although it may be just me!)

```
ggplot(data = linelist) +     # begin with linelist (many hospitals)
  
  # make histogram: specify bin break points: starts the Monday before first case, end Monday after last case
  geom_histogram(
    mapping = aes(
      x = date_onset,
      group = hospital,       # set data to be grouped by hospital
      fill = hospital),       # bar fill (inside color) by hospital
    
    # bin breaks are Monday weeks
    breaks = **weekly_breaks_all,**   # sequence of weekly Monday bin breaks for whole outbreak, defined in previous code       
    
    # Color around bars
    color = "black")
```

**Comment by nsbatra** [comment]
Thanks @PBBlomquist! In reviewing the section (23.3) I think the code is correct. This section is demonstrating a stacked epicurve by hospital, so the date breaks fed to geom_histogram() must be those for the whole outbreak, not only for the cases reported by Central Hospital. The data used are from all hospitals.  

Feel free to have them email epirhandbook@gmail.com if they want additional clarification or still think it is wrong.
