### ISSUE TITLE
Update github links in translations

### ISSUE THREAD

**Issue by nsbatra** [appliedepi/epiRhandbook_eng#2]
All translations need updated Github links: 
- Github link on Welcome page
- Almost all the links in the download data page

Use Find in Files tool to replace all:
epirhandbook/Epi_R_handbook to:
appliedepi/epirhandbook_eng

all the various pages that link to data (opening paragraphs)

**Comment by aspina7** [comment]
ideally do this at the same time as #6

**Comment by jarvisc1** [comment]
Closing issue as complete.
