### ISSUE TITLE
Is something wrong or missing in epicurves.Rmd ?

### ISSUE THREAD

**Issue by jcfernandezm** [appliedepi/epiRhandbook_eng#24]
Hola,

When rendering epicurves.Rmd (alone or the entire book). Gives that error.
I am using R 4.1.1 and incidence2 1.2.1 and later incidence 1.2.2

Error in (function (cond)  : 
  error in evaluating the argument 'x' in selecting a method for function 'plot': `cumulate()` was deprecated in incidence2 1.2.0 and is now defunct.
* See the 1.2.0 NEWS for more information

lines 757-760 epicurves.Rmd
# plot cumulative incidence
wkly_inci %>% 
cumulate() %>% 
  plot()
```

**Comment by nsbatra** [comment]
As this function cumulate() has been deprecated, I have removed this code chunk from the English and Vietnamese versions.
@jcfernandezm can you see the current website and adjust your translation accordingly?

**Comment by jcfernandezm** [comment]
Hola!. Yes, i will try later. We have had commented that lines before
because we can't render it. But are there some alternative to the
cumulative?

If I download the /english repository It will be on the RMD, isn'it

Un saludo!
   Juan Carlos
