### ISSUE TITLE
poorly formatted x-axis labels

### ISSUE THREAD

**Issue by SLGiHub** [appliedepi/epiRhandbook_eng#37]
in section "31.8 Highlighting" the x-axis labels are poorly formatted such that one can't read them clearly. ![image](https://user-images.githubusercontent.com/35525573/133891114-a55c056b-d389-4cbb-b722-376b73e563c9.png)!

Same problem in "31.11 Dual axes"

[image](https://user-images.githubusercontent.com/35525573/133891130-b4a4726b-ffd9-470e-8e80-9add5d41cf31.png)

Could have a piece on how to correctly format labels?

**Comment by aspina7** [comment]
hello @SLGiHub - thanks very much for pointing this out. Please see the section on [formatting time axes](https://epirhandbook.com/ggplot-tips.html#time-axes)
Hopefully this should clarify the possibilities for you! 
tagging @nsbatra in case you feel there is a need to add clarification (links) within the text?

**Comment by arranhamlet** [comment]
Updated to include a date formatting section to aid interpretation.
