### ISSUE TITLE
34.3 ordered y axis code doesn't change the y-axis order

### ISSUE THREAD

**Issue by pbkeating** [appliedepi/epiRhandbook_eng#42]
In the ordered y axis section of 34.3, the below code is used to order the location_name variable, however, this does not work. The location_name variable needs to be converted to a factor first and then fct_relevel will do what is expected.
You'll see that the current figures on the webpage with/without an ordered y-axis are identical.

Maybe also better to put the p_load(forcats) to the start of the chapter rather than in this chunk

`load package
pacman::p_load(forcats)

create factor and define levels manually
agg_weeks <- agg_weeks %>%
mutate(location_name = fct_relevel(
location_name, facility_order$location_name)
)`

**Comment by arranhamlet** [comment]
Updated, thank you for flagging this.
