### ISSUE TITLE
Cannot find the survey data used in 26.2

### ISSUE THREAD

**Issue by pbkeating** [appliedepi/epiRhandbook_eng#44]
Are there files available to run through the survey analysis section?
I couldn't find them after installing the handbook/or on github.
It would be helpful if such files were available to ensure users are getting the same results as presented online.

#import the survey data survey_data <- rio::import("survey_data.xlsx")

import the dictionary into R survey_dict <- rio::import("survey_dict.xlsx")

**Comment by pbkeating** [comment]
On the same note 26.8.4, the numbers presented for arrived, left and died are not really realistic and makes their interpretation more complicated than needed.

**Comment by aspina7** [comment]
this should be available if you follow the chapter on getting the datasets - will double check in next round though

**Comment by aspina7** [comment]
I eat my hat .... these datasets are not in the epirhandbook package. This will be fixed eventually .... three years later
