### ISSUE TITLE
New content for Factors page

### ISSUE THREAD

**Issue by nsbatra** [appliedepi/epiRhandbook_eng#45]
https://juliasilge.com/blog/reorder-within/

We should add something on this, perhaps at the end of the page as an advanced tip (or in ggplot2 tips page)

**Comment by nsbatra** [comment]
Actually, adding this is more important - adjusting factor levels of aggregated data points
https://stackoverflow.com/questions/52018079/changing-the-order-of-the-factors-on-the-plot-with-fct-infreq

**Comment by arranhamlet** [comment]
Added to the factors and ggplot basics chapters
