### ISSUE TITLE
Inconsistent code appearance in 42.5

### ISSUE THREAD

**Issue by pbkeating** [appliedepi/epiRhandbook_eng#46]
You can normally copy/paste most chunks of code from the book to R studio, but this is different in much of the page on flexdashboards. Unclear if this is intentional but ideally good to have chunks of code that can be copied rather than as images.

**Comment by nsbatra** [comment]
Thanks for raising this Pat. 

I made this page and recall that trying to include the entire flextable scripts as copyable, with YAML header, was preventing the page from rendering. So I was forced to do images. This had the benefit of allowing me to highlight parts of the image, which is nice.

Will revisit this upon revision stage.
