### ISSUE TITLE
Error in 42.6  plots - not possible to make the interactive epicurve 

### ISSUE THREAD

**Issue by pbkeating** [appliedepi/epiRhandbook_eng#47]
ggplotly no longer supports `levels.grates_yearweek()` which the incidence package uses and so the code for the interactive plot does not run.

It doesn't work with other packages - tsibble or aweek. Weeks or months are not supported by ggplotly

**Comment by nsbatra** [comment]
@isaac-florence do you have any time to investigate this and revise the interactive plots page if possible?
Really a shame if folks can't easily make interactive weekly epicurves.

**Comment by arranhamlet** [comment]
This has been updated in the latest version
