### ISSUE TITLE
More thorough explanation of barplot handling

### ISSUE THREAD

**Issue by nsbatra** [appliedepi/epiRhandbook_eng#49]
https://www.aj2duncan.com/blog/missing-data-ggplot2-barplots/
https://stackoverflow.com/questions/10834382/ggplot2-keep-unused-levels-barplot

Also make more clear in Factors page how o keep all levels in a plot. Note you may need to use scale_x_discrete drop=F, as well as scale_fill_ drop=F

how to deal with some values missing in some facets of barplots. 

the solution that worked for me was: 
  geom_col(position = position_dodge(preserve = 'single'))+

**Comment by nsbatra** [comment]
# maladies most seen
tout_slim <- tout %>% 
  filter(! indicateur %in% c(vals_age, vals_denom, vals_repro)) %>% 
  filter(sexe == "total") %>% 
  group_by(indicateur) %>% 
  summarise(
    cases = sum(value, na.rm=T)) %>% 
  filter(cases != 0) %>% 
  arrange(desc(cases))  

  
  ggplot(data = tout_slim, aes(x = fct_reorder(indicateur, cases), y = cases))+
  geom_col()+
  coord_flip()+
  scale_y_continuous(expand = c(0,0))+
  labs(x = "Maladie",
       y = "Nombre de patients",
       title = str_glue("Nombre de patients vus, par maladie (cumulatif) (n = {sum(tout_slim$cases, na.rm=T)})"),
       subtitle = str_glue("MSF-OCB clinique mobiles, Sud Departement, Haiti; donnees jusq'ua {format(max(tout$date, na.rm=T),'%d %b %Y')}"),
       caption = str_wrap(str_glue("Il y avait ZERO cas de: {str_c(indicateurs_zero, collapse = ', ')}"), 160))+
  theme_minimal(14)



On top of ensuring that the bars are the same width (see above), use complete(a, b) in the dataset ensures the bars are the  same position in each facet. See last comment in this:
https://stackoverflow.com/questions/11020437/consistent-width-for-geom-bar-in-the-event-of-missing-data

**Comment by arranhamlet** [comment]
This has been included in the latest update within the Factors chapter
