### ISSUE TITLE
Reduce size of all language repos

### ISSUE THREAD

**Issue by aspina7** [appliedepi/epiRhandbook_eng#6]
Follow this sequence of actions (see two linked issues below): 
- [ ] **_INFORM REPO COORDINATOR_**
- [ ] create empty repo with "_test" name extension (and fix language extension as per #10)
- [ ] clone new repo locally 
- [ ] transfer important files (remove things like *OLD*, etc.... **don't forget to keep index.Rmd and common.R!**)
- [ ] fix github links (as per #2) 
- [ ] push
- [ ] publish via netlify on "test domain" to see if book builds 
- [ ] edit name of old repo to replace "_test" with "_archive" (and archive the repo on github)
- [ ] edit name of new repo to have appropriate language ending (e.g. "_vn") 
- [ ] follow the digital ocean SOP for adding to the server 

Languages to complete: 
- [x] eng
- [x] vn
- [x] tr
- [ ] mn
- [x] es
- [x] jp
- [x] fr

**Comment by jarvisc1** [comment]
Closing old issue
