### ISSUE TITLE
Trouble with EpiNow2 Code

### ISSUE THREAD

**Issue by akarsteve** [appliedepi/epiRhandbook_eng#63]
The EpiNow2 code chunk below returned an error message:

## run epinow
epinow_res <- epinow(
  reported_cases = cases,
  generation_time = generation_time,
  delays = delay_opts(incubation_period),
  return_output = TRUE,
  verbose = TRUE,
  horizon = 21,
  stan = stan_opts(samples = 750, chains = 4)
)

Error Message:
Logging threshold set at INFO for the EpiNow2 logger
Writing EpiNow2 logs to the console and: C:\Users\AKARST~1\AppData\Local\Temp\RtmpcZOade/regional-epinow/2015-04-30.log
Logging threshold set at INFO for the EpiNow2.epinow logger
Writing EpiNow2.epinow logs to the console and: C:\Users\AKARST~1\AppData\Local\Temp\RtmpcZOade/epinow/2015-04-30.log
Error in seq.int(0, to0 - from, by) : 'to' must be a finite number
>

**Comment by akarsteve** [comment]
The linelist data worked with the EpiEstim package but produced errors all through for the EpiNow package. I do not know why.

**Comment by arranhamlet** [comment]
This package has been updated and should now correctly run.
