### ISSUE TITLE
Feedback: About this book

### ISSUE THREAD

**Issue by nsbatra** [appliedepi/epiRhandbook_eng#63]
**Please leave comments and suggested changes for the "About this book" pages here**

**Comment by nsbatra** [comment]
@Natalie-Fischer, @aspina7 , @dmolling can you please add short bullets to "new_pages/data_used.Rmd" about the datasets used in your respective pages? Thank you!

**Comment by ishaberry** [comment]
- Style and editorial notes: I wonder the heading about package and function names can come a bit later on this page? Maybe within coding style. If someone is relatively new to R some of the language may be a bit intimidating. Could also be good to briefly define package and function for clarity (or point to where these are defined in the Basics section 3.9).
- Wonder if when introducing tidyverse — could also help to have a line or two explaining why tidyverse, and how/why this is used. The term base R function is used in other sections so could be good to define here.

**Comment by nsbatra** [comment]
Great comments, thanks Isha. Implemented them.
