### ISSUE TITLE
Feedback: R Basics

### ISSUE THREAD

**Issue by nsbatra** [appliedepi/epiRhandbook_eng#64]
**Please leave comments and suggested changes for the "R Basics" page here**

**Comment by ishaberry** [comment]
Basics
- 3.1 + 3.14 Wonder if it would help to have the recommended training and help section moved up higher (into the overview/intro). If someone is super new to R this may be the first thing they need to see to better understand what they should do before using this handbook. 
- 3.7 — Some of the sections on R project may be better placed within the R projects page. Or having a note saying that more information on R projects is available on XXX.
-3.8.4 — typo I think meant to say Using $ on data frame…..
-3.9.2 — type in the Note: For arguments that you specify with both parts of the argument (e.g., proportional = TRUE)

**Comment by nsbatra** [comment]
Thanks @ishaberry , these have been fixed!

**Comment by daniellybx** [comment]
3.4 Instalation
We could include in this excerpt what versions of R and RSTudio we are using in the material, because some commands may work differently or not depending on the version.

**Comment by nsbatra** [comment]
@daniellybx thank you for these suggestions. I have made the changes and will push them to the website later today. 

I added a section with session and package information to the page "Datasets and versions used"
I have added your suggestions about RStudio etc.
And I added an example to the Objects section explaining how you can either save an object, or just print it (e.g. a table or plot)
I also added a section on equals signs.

Thanks in advance for more reviews!
