### ISSUE TITLE
Feedback: Importing and Exporting

### ISSUE THREAD

**Issue by nsbatra** [appliedepi/epiRhandbook_eng#65]
**Please leave comments and suggested changes for the "Importing and Exporting" page here**

**Comment by ishaberry** [comment]
-4.3 I think a little bit more comparison between the static and relative file path is needed. It is maybe not obviously clear that “data” “linelists” are the sub-folders identified in the static file path . This becomes clearer in the section but just having like a figure with a direct comparison could help?

**Comment by daniellybx** [comment]
Hello there! 

I have some sugestions:

5.13 File Paths
In the excerpt "Use forward slashes as in the example above (this is NOT the default for Windows file paths)", we can include that in RStudio on Windows, the command Ctrl + F allows the exchange of all slashes.
