### ISSUE TITLE
Epicurves updates

### ISSUE THREAD

**Issue by nsbatra** [appliedepi/epiRhandbook_eng#67]
Epicurves page:

Add to all ggplot chunks that use a `breaks = ` statement
    `closed = "left",                    # count cases from start of breakpoint`

Add bullet to explain its use, in Weekly Epicurve Example section
* We use `closed = "left"` in the `geom_histogram()` to ensure the date are counted in the correct bins  

Edit the multi-line date labels to include `labels = scales::label_date_short()`.

![image](https://user-images.githubusercontent.com/52152191/142255637-5abf2494-ec77-4f1f-9932-bada40c1a10b.png)

Remove one of the old examples using faceting. 
Edit the green faceting example to remove the facet panel border.

![image](https://user-images.githubusercontent.com/52152191/142255847-c92cf2f3-cdd4-4293-8213-50de602943e8.png)

Also this is updated in the ggplot tip page section on date axis. 
![image](https://user-images.githubusercontent.com/52152191/142257163-a3648dfc-e460-4f30-a9f2-d429c6c27ecd.png)

**Comment by arranhamlet** [comment]
This appears to have already been updated throughout
