### ISSUE TITLE
Feedback: Working with dates

### ISSUE THREAD

**Issue by nsbatra** [appliedepi/epiRhandbook_eng#67]
**Please leave comments and suggested changes for the "Working with dates" page here**

**Comment by nsbatra** [comment]
Maybe in the section on "Calculating distance between dates" we add an example of calculating age from a DOB?

**Comment by nsbatra** [comment]
@henryls1   Great page - this will be so useful. You write very clearly. 
Some thoughts:

-What do you think about starting the page with lubridate and moving base R as.Date() to afterwar ?
- I noticed that as_date() wasn't really introduced and neither was date()
- We'll need to expand the epiweeks section, including interplay between aweek and lubridate. And how to get Www-YYYY.  
-

**Comment by pbkeating** [comment]
From Alex's work on TSA, we use tsibble and `yearweek()` for epiweeks a lot in OCA. 

Could consider removing messages from the output in some chunks
