### ISSUE TITLE
40.4 Incomplete explanation of knitr option `child=` 

### ISSUE THREAD

**Issue by XimenaT** [appliedepi/epiRhandbook_eng#70]
Found a 'note to self' under File structure, subsection 'Source other files' (in chapter 40 section 4). It looks like the explanation for knitr option `child=` is incomplete or something was meant to be added here at a later stage. See image. 
Thank you for checking this!
![issue_ch40_2021-11-22](https://user-images.githubusercontent.com/38060920/142795552-1c158bba-0f78-49a4-b2aa-4b33ae8c728a.jpg)
e

**Comment by arranhamlet** [comment]
This has been updated in the latest version of the handbook
