### ISSUE TITLE
Bad links into common errors Rmd

### ISSUE THREAD

**Issue by jcfernandezm** [appliedepi/epiRhandbook_eng#71]
Into the pages Common errors, the links of interpreting error messages doesn't work.
In line 11 says [StackExchange.com](StackExchange.com), [stackoverflow.com](stackoverflow.com), [community.rstudio.com](community.rstudio.com)
and should be [StackExchange.com](https://stackexchange.com/), [stackoverflow.com](https://stackoverflow.com/), [community.rstudio.com](https://community.rstudio.com/)

**Comment by arranhamlet** [comment]
Thank you for flagging this, it has now been updated
