### ISSUE TITLE
37 Transmission chains - Error with subset()

### ISSUE THREAD

**Issue by CyGei** [appliedepi/epiRhandbook_eng#72]
In section **_37.3 Handling_**, the subset code produces an error:
`sub_attributes <- subset(
  epic,
  node_attribute = list(
    gender = "m",
    date_infection = as.Date(c("2014-04-01", "2014-07-01"))
  ), 
  edge_attribute = list(location = "Nosocomial")
)`
> _Error in FUN(X[[i]], ...) : 
 Value for date_infection is not found in dataset
In addition: Warning message:
In if (!attribute %in% data) stop(paste("Value for", name_attribute,  :
  the condition has length > 1 and only the first element will be used_

It looks like this is because the dates are stored as datetime when reading the "linelist_cleaned.xlsx" dataset. 

Adding the line below when reading the data fixes the problem:

`linelist <- rio::import("linelist_cleaned.xlsx") %>% 
  mutate(across(starts_with("date"), as.Date))`

**Comment by arranhamlet** [comment]
Thank you for flagging this, it has now been updated
