### ISSUE TITLE
Feedback: Descriptive analysis

### ISSUE THREAD

**Issue by nsbatra** [appliedepi/epiRhandbook_eng#74]
**Please leave comments and suggested changes for the "Descriptive analysis" page here**

**Comment by aspina7** [comment]
@nsbatra super comprehensive not much to add here, will come back to these comments and make a pr
- section 17.3: consider adding pros/cons for each of the functions (will think about this while going through code). 
E.g. things like:
tabyl requires post-processing to make publication or report- ready tables, and several steps to pull together a standard table, 
summarise/count - same as above but requires even more processing/manual handling (but maximum flexibility)
tbl_summary - doesnt include missings in percentage calculations, and more of a chore to extract values for ggplot
table - just the worst. 
- [multi-line tests](https://epirhandbook.com/descriptive-tables.html#across-multiple-columns) add a link to the statistical tests page at the bottom (just before section 17.7
- section 17.7 worth introducing the %$% pipe? (think it was this but the one we discussed on slack)
