### ISSUE TITLE
40.6 Parameterized example date mismatch YAML vs output image

### ISSUE THREAD

**Issue by XimenaT** [appliedepi/epiRhandbook_eng#75]
The date in YAML and the date that appears in the doc output do not match. YAML params date is 2021-04-10 but the date in the output image (see highlights in the attached image) is 2021-07-
![issue_ch40 6_2021-11-29](https://user-images.githubusercontent.com/38060920/143801015-df0fc538-f1b5-4c74-a645-6cf61f7e9d1a.jpg)
10

**Comment by arranhamlet** [comment]
Updated, thank you for flagging
