### ISSUE TITLE
Feedback: Simple statistical tests

### ISSUE THREAD

**Issue by nsbatra** [appliedepi/epiRhandbook_eng#75]
**Please leave comments and suggested changes for the "Simple statistical tests" page here**

**Comment by nsbatra** [comment]
Lead author is @aspina7

**Comment by Natalie-Fischer** [comment]
Hi Neale, 
Just a few comments here:

Maybe give a bit or introduction on when and why you would use each type of Analysis, what are the conclusions you can draw, what are the pitfalls (in a nutshell?)

17.3.1: Is there a way to remove these long numbers from the table 0.9300000000000000 ??
17.3.2: The output of the purrr table is not showing up here

**17.5 Multivariable:**
"For multivariable analysis you can use a combination there is not much difference between using gtsummary or broom to present the data" - check this sentence
" The workflow is the same for both, as **shown (?)** below, and only the last step of pulling a table together is different."

While this seems practical I think its not very transparent. As a beginner in using multivariate analysis I prefer to do my model in base and add the variables to the formula one by one and do forward selection. I think for the expert user this is great, I am just worried that people will just throw in all their variables together and see what they get without much knowledge about what they are actually doing. But I guess this goes beyond our scope here...

**17.6 Forest plot:**
" There are two options, you can build a plot yourself using ggplot2 or use a package called" - sentence incomplete
You did not load easystats in the preparations section

**Comment by aspina7** [comment]
**simple statistics page**
- [gtsummary intro](https://epirhandbook.com/simple-statistical-tests.html#gtsummary-package-1) "(described in section above)", guess this now reffers to the previous section (descriptive tables?)

**univariate and multivariate regression**
- Needs to be multivaria**ble**, multivariate refers is a commonly used but wrong as it refers to an analysis with multiple outcomes not multiple explanatory variables (see this [paper](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3518362/))
- [base r](https://epirhandbook.com/univariate-and-multivariate-regression.html#base-r-3) overview table, maybe worth adding a column with the common name for the regression (e.g. binomial = logistic)  
- lrtest - belive this produces the same output if just use a basic anova

**Comment by nsbatra** [comment]
Thanks for reviewing and flagging these issues @aspina7 . Happy to see you change these stats and regression pages however you see fit. I also think we need to add a section on linear regression somewhere in these pages.

**Comment by aspina7** [comment]
thanks @Natalie-Fischer  for reviewing, sorry for late response! See @nsbatra already did most of the legwork, making some changes now too
