### ISSUE TITLE
40.9 HTML widgets broken link to ch39

### ISSUE THREAD

**Issue by XimenaT** [appliedepi/epiRhandbook_eng#76]
The first bullet point refers to chapter 39 Interactive plots but there is a spelling issue (the 'c' in interactive is missing) see image. This has been addressed in the ES version
![issue_ch40_misspelled chap name_2021-11-29](https://user-images.githubusercontent.com/38060920/143801401-70fd30a3-2323-4e38-adf9-623b4096118a.jpg)

**Comment by arranhamlet** [comment]
Updated, thank you for flagging
