### ISSUE TITLE
Feedback: Standardization

### ISSUE THREAD

**Issue by nsbatra** [appliedepi/epiRhandbook_eng#76]
**Please leave comments and suggested changes for the "Standardization" page here**

**Comment by nsbatra** [comment]
Lead author is @lizacoyer

**Comment by nsbatra** [comment]
@lizacoyer see below some feedback from a reviewer. can you think about this?

**Suggestions for technical content of this page**
I think that there need to be a quick explanation about what you mean, statistically, by "standardisation" before diving into the rest (I guess in the "Overswiew-definition" section"). What we used to call standardisation back in stats in my field was to substract the mean of the variable, and divide by standard deviation, to make scales comparable. 

So I began reading the chapter and was completely lost: why do you mean, standardize by age? Why do you need a non cran package to do that? The formula is easy to use by hand, or there is always the scale function (or more elaborate packages https://cran.r-project.org/web/packages/standardize/vignettes/using-standardize.html ). 

Things were made even more difficult because the dsr package (the first in the list, so the first I googled) has not great documentation around. I am not sure I am fully 100% comfortable with this.

I think if you had spoken of adjusted rates or ratios I would have undestood a bit better (although I would have expected them coming from a more advanced statistical model controling for more things than, say, just age).

I guess that there must be some field dependant differences. If you think that all epis will have the same definition in mind (which is not the one present in stats books I read), then _maybe_ you could do without, but really I think a short explanation would be good.

In this more fleshed out description of standardisation in the Overview, you should define what the "standard population" population is (it is casually mentionned further, hidden in the "preparation" section). I had to _dig_ in the NIH link to get an idea of what it is (the reference population not, as I first thought, the official demographics of the country, but an hypothetic/ideal population)...


I think that what is missing from the chapter is an example of direct and indirect standardisation using base/tidyverse. Like you did in other chapters where you often show "manual" way of doing things and the "wrapped in a package" shortcut. I think there would be two advantages. The first one is that readers that either learned stats in another field or need to brush up their stats will be able to understand the logic of what is done (and then, maybe you don't have to explain so much more in the Overview. 
The second, it will help a bit descibing the method a bit better, because I am looking for dsr documentation, and I have troube finding it short of going to read the statistical references in the help page of the function, and really, I would expect a bit more that "go read four stats papers" when trying to figure out what a function does (especially for the confidence intervals). So far reading the function code has helped me more than anything, but we cannot expect that from all users.
So yeah, definitly show how to do it without a specific package, it will clarify averything I think.

**What else do you want to tell us?**
Hum, maybe a good part of the review come from me having learned stats in another field and may not be pertinent for epi readers. But I do stand on the non-package exemple, and on the CI explanations/additional ressources (I have read chapterS about GLMM and was yet wholly unprepared to the hell that is confidence intervals estimation for these models).

**Comment by lizacoyer** [comment]
@nsbatra Thanks! Yes, agreed we could give more background on standardisation in general, including standard population. I do want to avoid really getting into the statistics part of it though as maybe that goes beyond the scope of the handbook for Epis? Either way, I'll look into providing an example with base/tidyverse, this may already clear some things up. Such example will likely not include CIs though, as those are indeed trickier (and also beyond my knowledge of statistics tbh - I'm not sure if the goal of the page is to dig into all the CI functions, but keen to hear your take on that, perhaps a statistician contribute to that part if needed, I will make sure to at least mention the method used in each package on the page.)

I will also add another way of "adjusting" the rates for age/sex based on the population tables, using Poisson regression, which is maybe what the reviewer referred to with "more advanced model"? Whether one can "[control] for more things than, say, just age" really depends on how much info you have on population numbers in the different strata, which often does not go beyond age and sex - which I will add to the page too.

I think some of this also refers to a more general question - to what extent does the handbook aim to explain the Epi concepts & underlying calculations themselves? I totally agree with showing how to do calculations in R and giving some Epi background, but for the more detailed theory I think there are a lot of good Epi books already covering this. But curious to hear your thoughts!

**Comment by nsbatra** [comment]
Thanks @lizacoyer . I agree with you - this is an R handbook, not an epidemiology textbook. We should offer just enough explanation for the user to understand use cases for code and roughly how to interpret it, but not provide real statistical instruction. 

on the details I'll defer to you, as you know more than me. Thanks for making any updates you choose to!
