### ISSUE TITLE
Feedback: Plotting continuous data

### ISSUE THREAD

**Issue by nsbatra** [appliedepi/epiRhandbook_eng#80]
**Please leave comments and suggested changes for the "Plotting continuous data" page here**

Lead author is @PBBlomquist

**Comment by pbkeating** [comment]
Think need to remove **warning messages** in this chunk as they appear on the webpage

https://github.com/nsbatra/Epi_R_handbook/blob/7f3a905eced32f5b0cedb15c28243a12d915afc4/pages/plot_continuous.Rmd#L50

**Comment by pbkeating** [comment]
Since I haven't gone through the whole thing, do we explain somewhere about why write package::function?
https://github.com/nsbatra/Epi_R_handbook/blob/7f3a905eced32f5b0cedb15c28243a12d915afc4/pages/plot_continuous.Rmd#L110

**Comment by pbkeating** [comment]
Same extra bracket that could be removed
https://github.com/nsbatra/Epi_R_handbook/blob/7f3a905eced32f5b0cedb15c28243a12d915afc4/pages/plot_continuous.Rmd#L195

**Comment by pbkeating** [comment]
Something to consider, we have **ggtitle** here for titles and then **lab(title =** is used for ggplot and plotting categorical data. Obviously both work, in case we want to just use one way

https://github.com/nsbatra/Epi_R_handbook/blob/7f3a905eced32f5b0cedb15c28243a12d915afc4/pages/plot_continuous.Rmd#L205

**Comment by pbkeating** [comment]
Will need to remove warning message for this chunk as they appear on the page
https://github.com/nsbatra/Epi_R_handbook/blob/7f3a905eced32f5b0cedb15c28243a12d915afc4/pages/plot_continuous.Rmd#L215-L220

**Comment by pbkeating** [comment]
**Recreased**?? I need to read more.... what does this mean?
https://github.com/nsbatra/Epi_R_handbook/blob/7f3a905eced32f5b0cedb15c28243a12d915afc4/pages/plot_continuous.Rmd#L239
