### ISSUE TITLE
Feedback: Plotting categorical data

### ISSUE THREAD

**Issue by nsbatra** [appliedepi/epiRhandbook_eng#81]
**Please leave comments and suggested changes for the "Plotting categorical data" page here**

Lead author is @PBBlomquist

**Comment by pbkeating** [comment]
General comment, are we generally pushing towards use of pacman across the pages rather than install.packages?

https://github.com/nsbatra/Epi_R_handbook/blob/7f3a905eced32f5b0cedb15c28243a12d915afc4/pages/plot_discrete.Rmd#L60

**Comment by pbkeating** [comment]
Worth  mentioning in the Preparation section on table vs dplyr table the **useNA** argument with table so that the two tables shown both include missing values?

## 
##   Death Recover 
##    2582    1983

## # A tibble: 3 x 2
## # Groups:   outcome [3]
##   outcome     n
##   <chr>   <int>
## 1 Death    2582
## 2 Recover  1983
## 3 <NA>     1323

**Comment by pbkeating** [comment]
Extra bracket after tips can be removed
https://github.com/nsbatra/Epi_R_handbook/blob/7f3a905eced32f5b0cedb15c28243a12d915afc4/pages/plot_discrete.Rmd#L145

**Comment by pbkeating** [comment]
Apologies, I'm not doing this review in a systematic manner and just wondering if we'll cover or link to resources for more details on things like **theme** in the below and other things beyond basics?
https://github.com/nsbatra/Epi_R_handbook/blob/7f3a905eced32f5b0cedb15c28243a12d915afc4/pages/plot_discrete.Rmd#L163

**Comment by pbkeating** [comment]
Am assuming that **plot b** is coming soon to a page near you :)

https://github.com/nsbatra/Epi_R_handbook/blob/7f3a905eced32f5b0cedb15c28243a12d915afc4/pages/plot_discrete.Rmd#L227

**Comment by nsbatra** [comment]
Thanks @PBBlomquist! 
- Suggest moving the ggplot() section above the base R section, as we'd recommend most users use ggplot.
- @pbkeating In the handbook I've been pushing `pacman::p_load()` because it serves both the install and load functionality so well and can get github packages with p_load_gh(). I also find that beginners are confused by the differences in quotation use between install.packages() and library(). Both the pacman and install.packages and library approaches are explained in the R Basics page, but I'm happy to have this discussion on Slack if you think we should emphasize otherwise.   
- We will need to think how this categorical pltos page intersects with **factors** (not yet covered in the handbook and probably deserved its own page), as much of this content will also be covered in ggplot tips page. But I think categorical variables inherently need to discuss factors and ordering of stacked bars. 
- Yes @pbkeating we will address `theme` in the ggplot tips page.
- I like that you address coord_flip, as that is so useful with long categorical value names!
- Consider adding a small part about column width? 
- I'll submit some other suggestions via a pull request

**Comment by pbkeating** [comment]
@nsbatra Think great idea to promote pacman. My point was that we should be consistent as much as possible across pages and show pacman installation rather than install.packages once we've explained in the initial page the advantage of using pacman over install.packages
