### ISSUE TITLE
Feedback: Tables

### ISSUE THREAD

**Issue by nsbatra** [appliedepi/epiRhandbook_eng#82]
**Please leave comments and suggested changes for the "Tables" page here**

Lead author is @PBBlomquist

**Comment by pbkeating** [comment]
May need to remove the warning possibility on this first chunk of code as it doesn't show the code but rather the warning message

## `summarise()` has grouped output by 'hospital'. You can override using the `.groups` argument.

https://github.com/nsbatra/Epi_R_handbook/blob/1111f1c01d3536b5b785f468ec52845260bbb4f3/pages/tables.Rmd#L38-L50

**Comment by pbkeating** [comment]
Could spread this code over two rows for easier readability
https://github.com/nsbatra/Epi_R_handbook/blob/1111f1c01d3536b5b785f468ec52845260bbb4f3/pages/tables.Rmd#L189

**Comment by pbkeating** [comment]
This should be written as **border_remove** rather than border_removal

https://github.com/nsbatra/Epi_R_handbook/blob/1111f1c01d3536b5b785f468ec52845260bbb4f3/pages/tables.Rmd#L207

**Comment by pbkeating** [comment]
Out of curiosity, what does the **.** after bg( do in the below? Might be worth explaining in the text

https://github.com/nsbatra/Epi_R_handbook/blob/1111f1c01d3536b5b785f468ec52845260bbb4f3/pages/tables.Rmd#L250-L255

**Comment by pbkeating** [comment]
Would we not mention that the table could be included in a report as part of an Rmd?

https://github.com/nsbatra/Epi_R_handbook/blob/1111f1c01d3536b5b785f468ec52845260bbb4f3/pages/tables.Rmd#L284-L288

**Comment by pbkeating** [comment]
Not sure why the following appears at the bottom of this page

## [1] "C:/Users/Neale/OneDrive - Neale Batra/Documents/Analytic Software/R/Projects/R handbook/Epi_R_handbook/file.png"
