### ISSUE TITLE
Feedback: Diagrams

### ISSUE THREAD

**Issue by nsbatra** [appliedepi/epiRhandbook_eng#84]
**Please leave comments and suggested changes for the "Diagrams" page here**  

Lead author is @nsbatra

**Comment by pbkeating** [comment]
grViz([1249 chars quoted with '"']) show as code to copy for the section on complex examples below rather than the actual code. Same issue for sub-graph clusters

https://github.com/nsbatra/Epi_R_handbook/blob/1111f1c01d3536b5b785f468ec52845260bbb4f3/pages/diagrams.Rmd#L205-L216

**Comment by nsbatra** [comment]
Thanks @pbkeating  I hadn't noticed that the code folded up like this so the reader cannot copy it.
