### ISSUE TITLE
Feedback: Heatmaps

### ISSUE THREAD

**Issue by nsbatra** [appliedepi/epiRhandbook_eng#86]
**Please leave comments and suggested changes for the "Heatmaps & Density Plots" page here**  

Lead author is @nsbatra

**Comment by Natalie-Fischer** [comment]
Hi Neale, I have worked with heatmaps before, also using geomtiles so I thought I give this chapter a look. The GIS part seems still in development? Not sure. 

**34.1:** I would add the text from 34.3 to the Overview, as it give more a perspective on why we would want to use heatmaps.
**34.2**: I would either have a common preparation on top, or a separate preparation for parts 34.4 and 34.4. It seems a bit unorganized the way now you have several preparation sections. Do you want to add a description for the aweek package as well?
**34.3.1.1:** Did you forget to add the code for loading the dataset? 
**34.3.1.3 Aggregate and summarize**
An overall comment - for me personally I prefer going through the process step by step and having the corresponding code right under the step you are explaining in the text. I know that by piping its nice to have all done in one go, but for a beginner it may be a bit overwhelming. Just for your consideration. Breaking the code up also allows the learner to inspect the product after each step, which is kind of nice for a beginner as well.
"The floor_day = argument means that dates are rounded into the week only (day of the week is not shown)" - not clear to me what this means.
"Percent of the 7 days per facility-week for which data was reported" - not sure why this is in bold?
"= sum(malaria_tot, na.rm = T),   # total malaria cases reported" - add also why you do na.rm= T
 "group_by(location_name, week, .drop = F) %>%" --> maybe explain what .drop = F is for

I do not understand why you need step 5 with the right_join :-D It seems very complex - but maybe that is just me. Maybe ask somebody else if its clear to them for confirmation.

**34.3.2 Create heatmap**:
"The ggplot() is make using geom_tile():" - this sentence if off
"date_labels = "%d\n%b")+" --> explain formatting of date_labels? 

**34.3.2.2 Ordered y-axis:**
"If you want to order the y-axis facilities by **something**, convert them to class **F**actor and provide the order. "  factor not capital F. Something sounds very causal here - I would maybe rewrite to based on another variable or property. In the first chunk maybe give a bit more explanation on what you are doing. You are creating a new vector, where you calculate the days reported per each facility etc. 
"And now the data are re-plotted, with location_name being an ordered factor:" maybe mention that you are using the same code as above, so beginners won't look through and figure out what you have changed, but know its the dataset organization that changed.

**34.3.2.3 Display values:**
"Note the fillowing code added" --> typo in following
same sentence ". In" remove . and capital I
Check this whole sentence as it sounds confusing.

**34.4 GIS heatmaps:**
"Contoured heatmap of cases over a basemap" - can you write a whole sentence here? Or is this supposed to be a headline?
What are you going to do and show here? Needs more context.
You are loading open street map here again, but maybe better to load all packages in the preparation section.
Where do you load the dataset? Can we see the head of dataset first to see what lat and lon looks like?
I am sorry but this is not very well explained - maybe not finished yet? We don't know what zoom = TRUE means, or the what type refers to , or mergeTiles.

**Comment by nsbatra** [comment]
Hi Natalie, 
Thank you so much for these comments. 

I have addressed them as best I can at the moment. You can see the new version in the website now. 
I removed the GIS example entirely and transferred it over to the GIS page. I also tried to explain it more properly. 

I did add a new heat tile example - a transmission matrix! I think it is quite neat. I tried to go step-by-step more as you suggested.

Thanks again for your comments, happy to make other changes you see needed.

**Comment by Natalie-Fischer** [comment]
Hi Neale,

Much better. You did really well with the step by step :-) And I love the who infected who heatmap! Just a few typos I think.

Here my second review:

**Datasets:** Is linelist_cleaned.xlsx already available or would they have to go to the other section and create this linelist first themselves? This may be annoying.

**35.2:** 

- rename("infector_age_cat" = "age_cat")   # rename **for clarify** --> to clarify or for clarity?
- In the aesthetics aes() of geom_tile() **sex** the x and y as the case age and infector age --> set?

**35.3:**
I think you don't necessarily need to mention all the steps at first if you go then step by step. I like the step by step here!
 
# Group into facility-weeks
  group_by(
    location_name, week,
    .drop = F) %>% --> maybe add a note what .drop = F does?

The part on expanding and joining is much clearer to me now :-) 

I also like that you first show the basic plot and then the tuned plot with all the options.

**Comment by nsbatra** [comment]
Thanks @Natalie-Fischer , final revisions implemented!
