### ISSUE TITLE
Wrong colour

### ISSUE THREAD

**Issue by EKuki** [appliedepi/epiRhandbook_eng#86]
https://github.com/appliedepi/epiRhandbook_eng/blob/a5ab5f216f749535bb8531ae6f3e4ed1ab6abd39/new_pages/gis.Rmd#L111

Current versions reads: "The large red circles show health facility catchment areas of a certain radius"; however, it should read "The large BLACK circles show health facility catchment areas of a certain radius". 
Note that the circles are BLACK, not RED.

**Comment by arranhamlet** [comment]
Updated in the latest version
