### ISSUE TITLE
bad link

### ISSUE THREAD

**Issue by jcfernandezm** [appliedepi/epiRhandbook_eng#90]
At he end GIS page, of section 28.9 basemaps, the first link of "See the tutorials [here](http://data-analytics.net/cep/Schedule_files/geospatial.html) and here for more info." Doesn't goes. I have been looking at data-analytics it seems they have reestructure their space, there are one article in the blog and for in the tutorials related to geospatial

**Comment by arranhamlet** [comment]
Thank you for flagging this, it has now been updated
