### ISSUE TITLE
Bad link on chapter 16, section Resources

### ISSUE THREAD

**Issue by jcfernandezm** [appliedepi/epiRhandbook_eng#92]
The link in section Resources:
[purrr tips and tricks](https://www.hvitfeldt.me/blog/purrr-tips-and-tricks/)
doesn't work.
I have been looking at that page and it sems they have that document in
https://www.emilhvitfeldt.com/post/2018-01-08-purrr-tips-and-tricks/)

**Comment by arranhamlet** [comment]
Thank you for flagging this, it has now been updated
