### ISSUE TITLE
Bad link on chapter 19 section Univariate

### ISSUE THREAD

**Issue by jcfernandezm** [appliedepi/epiRhandbook_eng#93]
I think the link should be relative instead of absolute in

## Univariate {  }

Just like in the page on [Descriptive tables](https://epirhandbook.com/descriptive-tables.html)

In english it can be a problem if updated, but, in other languages allways is uncorrect

Un saludo

**Comment by arranhamlet** [comment]
Thank you for flagging this, it has now been updated
