### ISSUE TITLE
Bad links in chapter 19. Absolute address instead of relative

### ISSUE THREAD

**Issue by jcfernandezm** [appliedepi/epiRhandbook_eng#94]
I think the link should be relative instead of absolute in

## Univariate {  }
Just like in the page on [Descriptive tables](https://epirhandbook.com/descriptive-tables.html)

same problem in 
### **gtsummary** package {#reg_gt_uni .unnumbered}

Below we present the use of `tbl_uvregression()` from the **gtsummary** package. Just like in the page on [Descriptive tables](https://epirhandbook.com/descriptive-tables.html)

In english it can be a problem if updated, but, in other languages allways is uncorrect

Un saludo

**Comment by arranhamlet** [comment]
Thank you for flagging this, it has now been updated
