### ISSUE TITLE
Bad links in chapter 26 Survey analyisis

### ISSUE THREAD

**Issue by jcfernandezm** [appliedepi/epiRhandbook_eng#97]
All the links in the introduction of section "Descriptive Analysis" doesn't works.
26.7 Descriptive analysis

Basic descriptive analysis and visualisation is covered extensively in other chapters of the handbook, so we will not dwell on it here. For details see the chapters on [descriptive tables](https://epirhandbook.com/descriptive-tables.html), [statistical tests](https://epirhandbook.com/simple-statistical-tests.html), [tables for presentation](https://epirhandbook.com/tables-for-presentation.html), [ggplot basics](https://epirhandbook.com/ggplot-basics.html) and [R markdown reports](https://epirhandbook.com/r-markdown-reports.html).

... (some minutes later ...
I have had review the entire 26 chapter and there are many more links to epirhandbook tha doesn't goes, all of them are absolute links and it seems that the old epirhandbook.com address doesn't works properly)
Un saludo,

**Comment by arranhamlet** [comment]
Thank you for flagging this, it has now been updated
