### ISSUE TITLE
¿Bad reference in chapter 32?

### ISSUE THREAD

**Issue by jcfernandezm** [appliedepi/epiRhandbook_eng#99]
in the section https://epirhandbook.com/en/epidemic-curves.html#one-facet-with-data
there are a reference (and link) (see ggsave() in [ggplot tips](https://epirhandbook.com/en/ggplot-tips.html#ggplot-tips)).

I think the reference is bad, because there is nothing about ggsave into ggplot tips. But there are a tag into basics of ggplot

**Comment by arranhamlet** [comment]
Thank you for flagging this, it has now been updated
